# .bashrc

# This file is managed by Puppet.  If you modify it, your changes will be replaced in 30 minutes or less.

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
